name = "MoltenSaltThermodynamics"
uuid = "d4361f00-0c8d-11ea-2a9d-6df08e0aa564"
authors = ["doomphoenix-qxz <richardlfitzhugh@gmail.com>"]
version = "0.1.0"

[deps]
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
